language: php
php:
  - '7.1'
dist: precise
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
before_script:
  - composer self-update
  - composer install
script:
  - mkdir -p build/logs
  - chmod -R 777 build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry php vendor/bin/php-coveralls -v